#[phases.setup]
#aptPkgs = ["ffmpeg"]
#commands = ["export PATH=$PATH:/bin/ffmpeg",
#"echo 'ffmpeg installed at:' $(which ffmpeg)"
#]
#[phases.build]
[phases.setup]
aptPkgs = ['...', 'ffmpeg']

[phases.install]
commands = [
    "mkdir -p /app/bin",
    "cp $(which ffmpeg) /app/bin/",
    "go mod download"
]

[phases.build]
commands = [
    "export PATH=$PATH:/app/bin",
    "go build -o out",
    "ls /app",
    "ls /app/bin"
]
