#[phases.setup]
#aptPkgs = ["ffmpeg"]
#commands = ["export PATH=$PATH:/bin/ffmpeg",
#"echo 'ffmpeg installed at:' $(which ffmpeg)"
#]
#[phases.build]
[phases.setup]
aptPkgs = ['...', 'ffmpeg']

[phases.install]
commands = [
    "mkdir -p /app/bin",
    "cp $(which ffmpeg) /app/bin/",
    "cp /usr/lib/x86_64-linux-gnu/libavdevice.so.58 /app/bin/",
    "export PATH=$PATH:/app/bin",
    "go mod download",
    "which ffmpeg",
    "/app/bin/ffmpeg -version"
]

[phases.build]
commands = [
    "export PATH=$PATH:/app/bin",
    "go build -o out",
    "ls /app",
    "ls /app/bin",
    "ffmpeg -version"
]
