#[phases.setup]
#aptPkgs = ["ffmpeg"]
#commands = ["export PATH=$PATH:/bin/ffmpeg",
#"echo 'ffmpeg installed at:' $(which ffmpeg)"
#]
#[phases.build]
[phases.setup]
nixPkgs = ['...', 'ffmpeg']
#commands = [
#    "echo 'Installing dependencies and setting environment'",
#    "export PATH=$PATH:/usr/bin:/usr/local/bin:/bin:/bin/ffmpeg"
#]

#[phases.build]
#commands = [
#    "ls -la",
#]

#[phases.start]
#command = "./app"