#[phases.setup]
#aptPkgs = ["ffmpeg"]
#commands = ["export PATH=$PATH:/bin/ffmpeg",
#"echo 'ffmpeg installed at:' $(which ffmpeg)"
#]
#[phases.build]
[phases.setup]
aptPkgs = ["ffmpeg"]

[phases.build]
commands = [
    "echo 'Building Go application'",
    "go build -o app main.go",
    "ls -la",
    "echo 'Checking ffmpeg installation'",
    "which ffmpeg || echo 'ffmpeg not found'",
    "ffmpeg -version || echo 'ffmpeg not available'",
    "echo 'Current PATH:' $PATH"
]

[phases.start]
command = "./app"