# Настройки для установки пакетов и настройки окружения
[nixpkgs]

# Список пакетов, которые требуется установить
packages = ["ffmpeg"]

# Фазы установки и настройки окружения
[phases.setup]

# Выполняемые команды для подготовки окружения
commands = [
    # Команды для установки nixpkgs и пакетов из него
    "nixpacks setup",

    # Дополнительные команды для настройки окружения, если есть
]
#[start]
#cmd = "apt-get update && apt-get install -y ffmpeg && ./out"
