#[phases.setup]
#aptPkgs = ["ffmpeg"]
#commands = ["export PATH=$PATH:/bin/ffmpeg",
#"echo 'ffmpeg installed at:' $(which ffmpeg)"
#]
#[phases.build]
[phases.setup]
aptPkgs = ['...', 'ffmpeg']

[phases.install]
commands = [
    "mkdir -p /out/bin",
    "cp $(which ffmpeg) /out/bin/",
    "go mod download"
]

[phases.build]
commands = [
    "export PATH=$PATH:/out/bin",
    "go build -o out"
]
